### get goals
GET https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2OCwibmFtZSI6IkZBUklIIiwiZW1haWwiOiIxMTEyMDIzMTUxNDRAbWhzLmRpbnVzLmFjLmlkIiwiaWF0IjoxNzgwOTY2ODU5LCJleHAiOjE3ODEwNTMyNTl9.4GMVAUPgUp9XWZZ00pejVjkmtxA2fkI4qFbFXVbm2Y0

### post goals
POST https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2OCwibmFtZSI6IkZBUklIIiwiZW1haWwiOiIxMTEyMDIzMTUxNDRAbWhzLmRpbnVzLmFjLmlkIiwiaWF0IjoxNzgwOTY2ODU5LCJleHAiOjE3ODEwNTMyNTl9.4GMVAUPgUp9XWZZ00pejVjkmtxA2fkI4qFbFXVbm2Y0
Content-Type: application/json

{
  "target_amount": 100000,
  "present_amount": 25000
}